// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"context"
)

type Querier interface {
	CreateURL(ctx context.Context, arg CreateURLParams) (int32, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetURLByID(ctx context.Context, id int32) (Url, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserURLS(ctx context.Context, userID int32) ([]Url, error)
	SetShortURLByID(ctx context.Context, arg SetShortURLByIDParams) error
}

var _ Querier = (*Queries)(nil)
