CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "full_name" varchar NOT NULL,
  "password" varchar NOT NULL
);

CREATE TABLE "urls" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "short_uri" varchar UNIQUE,
  "user_id" int NOT NULL,
  "requested_count" int NOT NULL DEFAULT 0,
  "original_url" text NOT NULL,
  "expires_at" timestamptz NOT NULL
);

CREATE UNIQUE INDEX ON "users" ("id");

CREATE UNIQUE INDEX ON "users" ("username");

CREATE INDEX ON "urls" ("short_uri");

CREATE INDEX ON "urls" ("user_id");

CREATE INDEX ON "urls" ("expires_at");

ALTER TABLE "urls" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");